# Generated by Django 5.2.1 on 2025-06-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=32)),
                ('s_ts', models.DateTimeField()),
                ('s_done', models.BooleanField(default=False)),
                ('s_from', models.CharField()),
                ('s_to', models.CharField()),
            ],
        ),
    ]
