# Generated by Django 5.2.1 on 2025-06-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipments',
            old_name='s_ts',
            new_name='s_start_ts',
        ),
        migrations.AddField(
            model_name='shipments',
            name='s_end_ts',
            field=models.DateTimeField(null=True),
        ),
    ]
